# Generated by Django 2.1.2 on 2018-10-16 19:47

import cloudinary.models
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=30)),
                ('cover', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('release_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=30)),
                ('loan_date', models.DateTimeField()),
                ('retrieval_date', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon2.Book')),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.SmallIntegerField()),
                ('comment', models.CharField(max_length=600)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon2.Loan')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='BookOwner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon2.BookOwner'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='amazon2.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon2.BookOwner'),
        ),
    ]
