# Generated by Django 2.1.2 on 2018-10-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Loaned', 'Loaned')], max_length=30),
        ),
    ]
