# Generated by Django 2.1.2 on 2018-10-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon2', '0003_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(default='New', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
