# Generated by Django 2.1.2 on 2018-10-19 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon2', '0003_auto_20181016_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('Seen', 'Seen')], max_length=15)),
                ('message', models.CharField(max_length=600)),
                ('time_sent', models.DateTimeField()),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='amazon2.Book')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='amazon2.BookOwner')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='amazon2.BookOwner')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
