# Generated by Django 2.1.2 on 2018-10-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon2', '0004_auto_20181014_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='loan_id',
            new_name='loan',
        ),
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AddField(
            model_name='review',
            name='ŗeview_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
