# Generated by Django 2.1.2 on 2018-10-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon2', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Damaged', 'Damaged')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='amazon2.Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Loaned', 'Loaned')], max_length=30),
        ),
    ]
